<?
$PERM["upload"]["5"]="R";
$PERM["upload"]["7"]="W";
$PERM["upload"]["8"]="W";
$PERM["help"]["8"]="W";
$PERM["personal"]["8"]="W";
$PERM["catalog"]["8"]="W";
$PERM["news"]["8"]="W";
$PERM["news"]["27"]="W";
$PERM["include"]["8"]="W";
$PERM["company"]["8"]="W";
$PERM["about"]["8"]="W";
$PERM["index.php"]["8"]="W";
$PERM["desktop_app"]["*"]="D";
$PERM["online"]["*"]="R";
$PERM["pub"]["5"]="T_8";
$PERM["/"]["*"]="R";
?>