<?
require __DIR__ . '/config.php';

$sberbank_ecom2_default_option = array(
	'BANK_NAME' => $SBERBANK_CONFIG['BANK_NAME'],
	'MODULE_ID' => $SBERBANK_CONFIG['MODULE_ID'],
	'SBERBANK_PROD_URL' => $SBERBANK_CONFIG['SBERBANK_PROD_URL'],
	'SBERBANK_TEST_URL' => $SBERBANK_CONFIG['SBERBANK_TEST_URL'],
	'MODULE_VERSION' => $SBERBANK_CONFIG['MODULE_VERSION'],
	'ISO' => serialize($SBERBANK_CONFIG['ISO']),
	'RESULT_ORDER_STATUS' => 'FALSE',
	'OPTION_PHONE' => 'PHONE',
	'OPTION_EMAIL' => 'EMAIL',
	'OPTION_FIO' => 'FIO',
	'TAX_DEFAULT' => 6,
	'CALLBACK_ENABLED' => serialize(array()),
	'AUTO_REDIRECT_EXCEPTIONS' => serialize(array(
		'/personal/orders/'
	)),
	'IGNORE_PRODUCT_TAX' => $SBERBANK_CONFIG['IGNORE_PRODUCT_TAX'],
	'DISCOUNT_HELPER' =>  $SBERBANK_CONFIG['DISCOUNT_HELPER'],
	'MEASUREMENT_CODE' => $SBERBANK_CONFIG['MEASUREMENT_CODE'],
	'RBS_ENABLE_CALLBACK' => $SBERBANK_CONFIG['RBS_ENABLE_CALLBACK'],
	'CANCEL_ORDER_BY_TIMEOUT' => $SBERBANK_CONFIG['CANCEL_ORDER_BY_TIMEOUT'],

);

?>